function make_isotropic_niis( path, R, train_bool )
%MAKE_ISOTROPIC_NIIS Summary of this function goes here
%   Detailed explanation goes here

    %reslice 20s image to be isotropic
    reslice_nii([path,'/nii_files/20s.nii.gz'],...
        [path,'/nii_files/20s_isotropic.nii.gz'],...
        [R,R,R]);

    %reslice pre image to be isotropic
    reslice_nii([path,'/nii_files/pre_reg.nii'],...
        [path,'/nii_files/pre_reg_isotropic.nii'],...
        [R,R,R]);

    %reslice 70s to be isotropic 
    reslice_nii([path,'/nii_files/70s_reg.nii'],...
        [path,'/nii_files/70s_reg_isotropic.nii'],...
        [R,R,R]);

    %reslice whole liver segmentation to be isotropic 
    reslice_nii([path,'/nii_files/whole_liver.nii'],...
        [path,'/nii_files/whole_liver_isotropic.nii'],...
        [R,R,R]);

    %reslice t2 image bias field estimate to be isotropic 
    reslice_nii([path,'/nii_files/t2_bfc_reg.nii'],...
        [path,'/nii_files/t2_bfc_reg_isotropic.nii'],...
        [R,R,R]);

    if train_bool
        %reslice vessel segmentation to be isotropic 
        reslice_nii([path,'/nii_files/vessel.nii'],...
            [path,'/nii_files/vessel_isotropic.nii'],...
            [R,R,R]);

        %reslice necrosis segmentation to be isotropic 
        reslice_nii([path,'/nii_files/necrosis.nii'],...
            [path,'/nii_files/necrosis_isotropic.nii'],...
            [R,R,R]);

        %reslice tumor segmentation to be isotropic 
        reslice_nii([path,'/nii_files/tumor.nii'],...
            [path,'/nii_files/tumor_isotropic.nii'],...
            [R,R,R]);
    end

end

